services:
  tcm:
    image: my-application
    networks:
    - cluster_network
    environment:
    - TCM_HTTP_HOST=0.0.0.0
    - TCM_STORAGE_ETCD_EMBED_ENDPOINTS=http://0.0.0.0:2379
    - TCM_STORAGE_ETCD_EMBED_ADVERTISES=http://0.0.0.0:2379
    - TCM_STORAGE_ETCD_EMBED_PEER_ENDPOINTS=http://0.0.0.0:2380
    - TCM_STORAGE_ETCD_EMBED_PEER_ADVERTISES=http://0.0.0.0:2380
    - TCM_STORAGE_ETCD_ENDPOINTS=http://0.0.0.0:2379
    command: >
        bash -c "source tarantool-enterprise/env.sh
        && ./tcm --storage.etcd.embed.enabled"
    ports:
      - "8080:8080"
      - "80:80"
      - "2379:2379"
      - "2380:2380"

  tarantool:
    image: my-application
    networks:
    - cluster_network
    command: >
        bash -c "source tarantool-enterprise/env.sh
        && tt cluster publish "http://tcm:2379/default" instances.enabled/sharded_cluster_tcm/cluster.yaml --force
        && tt build sharded_cluster_tcm
        && tt start sharded_cluster_tcm
        && tail -f /dev/null"
    ports:
      - "3301:3301"
      - "3302:3302"
      - "3303:3303"
      - "3304:3304"
      - "3312:3312"
      - "3313:3313"
      - "3314:3314"
    depends_on:
      - tcm

#  failover_coordinator:
#    image: my-application
#    networks:
#    - cluster_network
#    command: >
#        bash -c "source tarantool-enterprise/env.sh
#        && tarantool --failover --config instances.enabled/sharded_cluster_tcm/config.yaml > /dev/null"
#    depends_on:
#      - tcm
#      - tarantool
networks:
  cluster_network:
    name: cluster_network
    driver: bridge
